namespace Slippi.NET.Melee.Types;

public enum Character : int
{
    CaptainFalcon = 0,
    DonkeyKong = 1,
    Fox = 2,
    GameAndWatch = 3,
    Kirby = 4,
    Bowser = 5,
    Link = 6,
    Luigi = 7,
    Mario = 8,
    Marth = 9,
    Mewtwo = 10,
    Ness = 11,
    Peach = 12,
    Pikachu = 13,
    IceClimbers = 14,
    JigglyPuff = 15,
    Samus = 16,
    Yoshi = 17,
    Zelda = 18,
    Sheik = 19,
    Falco = 20,
    YoungLink = 21,
    DrMario = 22,
    Roy = 23,
    Pichu = 24,
    Ganondorf = 25,
    MasterHand = 26,
    WireframeMale = 27,
    WireframeFemale = 28,
    GigaBowser = 29,
    CrazyHand = 30,
    Sandbag = 31,
    Popo = 32
}
