namespace Slippi.NET.Types;

[Flags]
public enum EnabledItemType : ulong
{
    METAL_BOX = ((ulong)1) << 0,
    CLOAKING_DEVICE = ((ulong)1) << 1,
    POKEBALL = ((ulong)1) << 2,
    UNKNOWN_ITEM_BIT_4 = ((ulong)1) << 3,
    UNKNOWN_ITEM_BIT_5 = ((ulong)1) << 4,
    UNKNOWN_ITEM_BIT_6 = ((ulong)1) << 5,
    UNKNOWN_ITEM_BIT_7 = ((ulong)1) << 6,
    UNKNOWN_ITEM_BIT_8 = ((ulong)1) << 7,
    FAN = ((ulong)1) << 8,
    FIRE_FLOWER = ((ulong)1) << 9,
    SUPER_MUSHROOM = ((ulong)1) << 10,
    POISON_MUSHROOM = ((ulong)1) << 11,
    HAMMER = ((ulong)1) << 12,
    WARP_STAR = ((ulong)1) << 13,
    SCREW_ATTACK = ((ulong)1) << 14,
    BUNNY_HOOD = ((ulong)1) << 15,
    RAY_GUN = ((ulong)1) << 16,
    FREEZIE = ((ulong)1) << 17,
    FOOD = ((ulong)1) << 18,
    MOTION_SENSOR_BOMB = ((ulong)1) << 19,
    FLIPPER = ((ulong)1) << 20,
    SUPER_SCOPE = ((ulong)1) << 21,
    STAR_ROD = ((ulong)1) << 22,
    LIPS_STICK = ((ulong)1) << 23,
    HEART_CONTAINER = ((ulong)1) << 24,
    MAXIM_TOMATO = ((ulong)1) << 25,
    STARMAN = ((ulong)1) << 26,
    HOME_RUN_BAT = ((ulong)1) << 27,
    BEAM_SWORD = ((ulong)1) << 28,
    PARASOL = ((ulong)1) << 29,
    GREEN_SHELL = ((ulong)1) << 30,
    RED_SHELL = ((ulong)1) << 31,
    CAPSULE = ((ulong)1) << 32,
    BOX = ((ulong)1) << 33,
    BARREL = ((ulong)1) << 34,
    EGG = ((ulong)1) << 35,
    PARTY_BALL = ((ulong)1) << 36,
    BARREL_CANNON = ((ulong)1) << 37,
    BOMB_OMB = ((ulong)1) << 38,
    MR_SATURN = ((ulong)1) << 39
}