<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Slippi.NET\Slippi.NET.csproj" />
	<ProjectReference Include="..\DolphinENet\DolphinENet.vcxproj">
		<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		<OutputItemType>Content</OutputItemType>
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</ProjectReference>
  </ItemGroup>

</Project>
